# Generated by Django 5.0.2 on 2024-02-19 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('money', models.PositiveIntegerField(verbose_name='Желаемая зарплата')),
                ('skill', models.TextField(help_text='Напишите что умеете', verbose_name='Навыки')),
                ('education', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Образование')),
                ('registred_in', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='рабодатель')),
                ('position', models.CharField(max_length=128, verbose_name='должность')),
                ('duty', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('started_in', models.DateField(verbose_name='Начал работь')),
                ('finished_in', models.DateField(blank=True, null=True, verbose_name='Закончил работь')),
                ('registred_in', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaves.resume', verbose_name='резюме')),
            ],
        ),
    ]
